### PR TITLE
Export not undefined utility type

### PR DESCRIPTION
**Pull request by iliaamiri**
I was implementing a function that had a generic type to pass to the `Either<T>` and I had a type error basically saying `T` cannot be `undefined`. So, I had define my own version of the `NotUndefined<T>` utility we have in `might-fail/ts`.

```ts
type Defined<T> = T extends undefined ? never : T;

// vs. I should be able to import it from the library as a utility type
// import { NotUndefined } from 'might-fail'
// or 
// import { NotUndefined } from 'might-fail/go'

async function tryManyTimes<T>(callback: (currentTry: number) => Promise<Either<Defined<T>>>, options: { maxTries: number; delay: number }, currentTry = 1) {
    const [error, result] = await callback(currentTry);
    if (error) {
        await wait(options.delay);

        if (currentTry > options.maxTries) {
            return Fail(error);
        }

        return tryManyTimes(callback, options, currentTry + 1);
    }

    return Might(result);
}
```

### CODE REVIEW

**Comment by meech-ward** [comment]
That looks kind of gross, having to manually add NotUndefined to a function like that. 

could/should we do something like this

```ts
import { NotUndefined } from "./utils/utils.type"

/**
 * Either type represents a data structure that encapsulates a successful result or an Error.
 * It wraps the result of a Promise in an object, making it easier to handle errors by returning
 * an object that either contains a 'result' value of type T (if successful), or an 'error' of type Error.
 *
 * @template T The type of the result value.
 */
export type Either<NotUndefined<T>> =
  | ({
      error: Error
      result: undefined
    } & [Error, undefined])
  | ({
      result: T
      error: undefined
    } & [undefined,T])
```

**Comment by iliaamiri** [comment]
Should we fully switch away to `null`. Because `NotUndefined<T>` 's empty version would be `null`

**Comment by meech-ward** [comment]
Maybe! TS does a lot to help out here so maybe it's ok if the type can be undefined

* error will be `Error` if there's an error, or `undefined` if there's no error
* result will be `undefined` if there's an error, or `T` if there's no error. `T` is undefined if you want it to be, it's completely up to you

it does mean that guarding is a requirement

```ts
// bad way to check if there was an error or not
if (result) {
 // do result stuff
} else {
 // do error stuff
}
```

```ts
// good way to check for error 
if (error) {
 // handle error
  return 
}
// maybe you also have a result, I don’t care
```

**Comment by iliaamiri** [comment]
@meech-ward I removed the NotUndefined type and there were also some type issues with the `MightFailFunction` in Go version which is fixed now too. The types were not compatible cause of the `Awaited` type added.

**Comment by meech-ward** [comment]
I forgot about this. is this good to merge?

**Comment by iliaamiri** [comment]
Np yeah it should be ready

**Pull request merged**
